import { BoardGameSeedData } from "@/types/board-game";

export const boardGameData: BoardGameSeedData[] = [
	{
		title: "Arcs",
		slug: "arcs",
		publisherName: "Leder Games",
		designerName: "Cole Wehrle",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["science-fiction", "space-exploration", "wargame"],
		mechanicSlugs: [
			"area-majority-influence",
			"area-movement",
			"campaign-battle-card-driven",
			"dice-rolling",
			"die-icon-resolution",
			"hand-management",
			"take-that",
			"trick-taking",
			"turn-order-claim-action",
			"variable-player-powers",
		],
	},
	{
		title: "Bananagrams",
		slug: "bananagrams",
		publisherName: "Bananagrams, Inc.",
		designerName: "Rena Nathanson",
		minPlayers: 1,
		maxPlayers: 8,
		categorySlugs: ["real-time", "word-game"],
		mechanicSlugs: ["race", "spelling", "tile-placement"],
	},
	{
		title: "Blue Lagoon",
		slug: "blue-lagoon",
		publisherName: "Blue Orange Games",
		designerName: "Reiner Knizia",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["abstract-strategy"],
		mechanicSlugs: [
			"area-majority-influence",
			"chaining",
			"connections",
			"end-game-bonuses",
			"hexagon-grid",
			"network-and-route-building",
			"score-and-reset-game",
			"set-collection",
			"variable-set-up",
		],
	},
	{
		title: "Boggle",
		slug: "boggle",
		publisherName: "Alga",
		designerName: "Bill Cooke",
		minPlayers: 1,
		maxPlayers: 8,
		categorySlugs: ["real-time", "word-game"],
		mechanicSlugs: [
			"dice-rolling",
			"spelling",
		],
	},
	{
		title: "Boss Monster: The Dungeon Building Card Game",
		slug: "boss-monster-the-dungeon-building-card-game",
		publisherName: "Brotherwise Games",
		designerName: "Johnny O'Neal",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["card-game", "fantasy", "video-game"],
		mechanicSlugs: [
			"hand-management",
			"player-elimination",
			"take-that",
			"variable-player-powers",
		],
	},
	{
		title: "Boss Monster 2: The Next Level",
		slug: "boss-monster-2-the-next-level",
		publisherName: "Brotherwise Games",
		designerName: "Johnny O'Neal",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: [
			"card-game",
			"city-building",
			"expansion-for-base-game",
			"fantasy",
			"video-game",
		],
		mechanicSlugs: [
			"auction-bidding",
			"hand-management",
			"player-elimination",
			"take-that",
		],
	},
	{
		title: "Boss Monster: Paper & Pixels",
		slug: "boss-monster-paper-and-pixels",
		publisherName: "Brotherwise Games",
		designerName: "Johnny O'Neal",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: [
			"card-game",
			"expansion-for-base-game",
			"fantasy",
			"video-game",
		],
		mechanicSlugs: [
			"auction-bidding",
			"hand-management",
			"player-elimination",
			"take-that",
			"variable-player-powers",
		],
	},
	{
		title: "Boss Monster: Tools of Hero-Kind",
		slug: "boss-monster-tools-of-hero-kind",
		publisherName: "Brotherwise Games",
		designerName: "Johnny O'Neal",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: [
			"card-game",
			"city-building",
			"expansion-for-base-game",
			"fantasy",
			"video-game",
		],
		mechanicSlugs: [
			"auction-bidding",
			"hand-management",
			"player-elimination",
			"take-that",
		],
	},
	{
		title: "Brass: Birmingham",
		slug: "brass-birmingham",
		publisherName: "Roxley",
		designerName: "Gavan Brown",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: [
			"economic",
			"industry-manufacturing",
			"trains",
			"transportation",
		],
		mechanicSlugs: [
			"chaining",
			"end-game-bonuses",
			"hand-management",
			"income",
			"loans",
			"market",
			"multi-use-cards",
			"network-and-route-building",
			"tech-trees-tech-tracks",
			"tile-placement",
			"turn-order-stat-based",
			"variable-set-up",
		],
	},
	{
		title: "Cat in the Box: Deluxe Edition",
		slug: "cat-in-the-box-deluxe-edition",
		publisherName: "Hobby Japan",
		designerName: "Muneyuki Yokouch",
		minPlayers: 2,
		maxPlayers: 5,
		categorySlugs: ["animals", "card-game"],
		mechanicSlugs: ["hand-management", "predictive-bid", "trick-taking"],
	},
	{
		title: "Clank! In! Space!: A Deck-Building Adventure",
		slug: "clank-in-space-a-deck-building-adventure",
		publisherName: "Dire Wolf",
		designerName: "Paul Dennen",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["science-fiction"],
		mechanicSlugs: [
			"deck-bag-and-pool-building",
			"delayed-purchase",
			"modular-board",
			"open-drafting",
			"player-elimination",
			"point-to-point-movement",
			"push-your-luck",
		],
	},
	{
		title: "Clank! Legacy: Acquisitions Incorporated",
		slug: "clank-legacy-acquisitions-incorporated",
		publisherName: "Dire Wolf",
		designerName: "Paul Dennen",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["adventure", "fantasy",],
		mechanicSlugs: [
			"deck-bag-and-pool-building",
			"delayed-purchase",
			"end-game-bonuses",
			"events",
			"legacy-game",
			"map-addition",
			"movement-points",
			"narrative-choice-paragraph",
			"once-per-game-abilities",
			"open-drafting",
			"pick-up-and-deliver",
			"player-elimination",
			"point-to-point-movement",
			"push-your-luck",
			"scenario-mission-campaign-game",
			"set-collection",
			"variable-player-powers",
			"variable-set-up",
		],
	},
];
