import { Seeder } from "./Seeder";
import type { BoardGameSeedData } from "@/types/seed/board-game";

export const boardGameData: BoardGameSeedData[] = [
	{
		...Seeder.generateTitleWithSlug("Arcs"),
		publisherName: "Leder Games",
		designerName: "Cole Wehrle",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["science-fiction", "space-exploration", "wargame"],
		mechanicSlugs: [
			"area-majority-influence",
			"area-movement",
			"campaign-battle-card-driven",
			"dice-rolling",
			"die-icon-resolution",
			"hand-management",
			"take-that",
			"trick-taking",
			"turn-order-claim-action",
			"variable-player-powers",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Bananagrams"),
		publisherName: "Bananagrams, Inc.",
		designerName: "Rena Nathanson",
		minPlayers: 1,
		maxPlayers: 8,
		categorySlugs: ["real-time", "word-game"],
		mechanicSlugs: ["race", "spelling", "tile-placement"],
	},
	{
		...Seeder.generateTitleWithSlug("Blue Lagoon"),
		publisherName: "Blue Orange Games",
		designerName: "Reiner Knizia",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["abstract-strategy"],
		mechanicSlugs: [
			"area-majority-influence",
			"chaining",
			"connections",
			"end-game-bonuses",
			"hexagon-grid",
			"network-and-route-building",
			"score-and-reset-game",
			"set-collection",
			"variable-set-up",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Boggle"),
		publisherName: "Alga",
		designerName: "Bill Cooke",
		minPlayers: 1,
		maxPlayers: 8,
		categorySlugs: ["real-time", "word-game"],
		mechanicSlugs: ["dice-rolling", "spelling"],
	},
	{
		...Seeder.generateTitleWithSlug(
			"Boss Monster: The Dungeon Building Card Game"
		),
		publisherName: "Brotherwise Games",
		designerName: "Johnny O'Neal",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["card-game", "fantasy", "video-game"],
		mechanicSlugs: [
			"hand-management",
			"player-elimination",
			"take-that",
			"variable-player-powers",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Boss Monster 2: The Next Level"),
		publisherName: "Brotherwise Games",
		designerName: "Johnny O'Neal",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: [
			"card-game",
			"city-building",
			"expansion-for-base-game",
			"fantasy",
			"video-game",
		],
		mechanicSlugs: [
			"auction-bidding",
			"hand-management",
			"player-elimination",
			"take-that",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Boss Monster: Paper & Pixels"),
		publisherName: "Brotherwise Games",
		designerName: "Johnny O'Neal",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: [
			"card-game",
			"expansion-for-base-game",
			"fantasy",
			"video-game",
		],
		mechanicSlugs: [
			"auction-bidding",
			"hand-management",
			"player-elimination",
			"take-that",
			"variable-player-powers",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Boss Monster: Tools of Hero-Kind"),
		publisherName: "Brotherwise Games",
		designerName: "Johnny O'Neal",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: [
			"card-game",
			"city-building",
			"expansion-for-base-game",
			"fantasy",
			"video-game",
		],
		mechanicSlugs: [
			"auction-bidding",
			"hand-management",
			"player-elimination",
			"take-that",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Brass: Birmingham"),
		publisherName: "Roxley",
		designerName: "Gavan Brown",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: [
			"economic",
			"industry-manufacturing",
			"trains",
			"transportation",
		],
		mechanicSlugs: [
			"chaining",
			"end-game-bonuses",
			"hand-management",
			"income",
			"loans",
			"market",
			"multi-use-cards",
			"network-and-route-building",
			"tech-trees-tech-tracks",
			"tile-placement",
			"turn-order-stat-based",
			"variable-set-up",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Cat in the Box: Deluxe Edition"),
		publisherName: "Hobby Japan",
		designerName: "Muneyuki Yokouch",
		minPlayers: 2,
		maxPlayers: 5,
		categorySlugs: ["animals", "card-game"],
		mechanicSlugs: ["hand-management", "predictive-bid", "trick-taking"],
	},
	{
		...Seeder.generateTitleWithSlug(
			"Clank! In! Space!: A Deck-Building Adventure"
		),
		publisherName: "Dire Wolf",
		designerName: "Paul Dennen",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["science-fiction"],
		mechanicSlugs: [
			"deck-bag-and-pool-building",
			"delayed-purchase",
			"modular-board",
			"open-drafting",
			"player-elimination",
			"point-to-point-movement",
			"push-your-luck",
		],
	},
	{
		...Seeder.generateTitleWithSlug(
			"Clank! Legacy: Acquisitions Incorporated"
		),
		publisherName: "Dire Wolf",
		designerName: "Paul Dennen",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["adventure", "fantasy"],
		mechanicSlugs: [
			"deck-bag-and-pool-building",
			"delayed-purchase",
			"end-game-bonuses",
			"events",
			"legacy-game",
			"map-addition",
			"movement-points",
			"narrative-choice-paragraph",
			"once-per-game-abilities",
			"open-drafting",
			"pick-up-and-deliver",
			"player-elimination",
			"point-to-point-movement",
			"push-your-luck",
			"scenario-mission-campaign-game",
			"set-collection",
			"variable-player-powers",
			"variable-set-up",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Hive"),
		publisherName: "Gen42 Games",
		designerName: "John Yianni",
		minPlayers: 2,
		maxPlayers: 2,
		categorySlugs: ["abstract-strategy", "animals"],
		mechanicSlugs: ["hexagon-grid", "pieces-as-map", "tile-placement"],
	},
	{
		...Seeder.generateTitleWithSlug(
			"221B Baker Street: The Master Detective Game"
		),
		publisherName: "Gameology",
		designerName: "Jay Moriarty",
		minPlayers: 2,
		maxPlayers: 6,
		categorySlugs: ["deduction", "murder-mystery", "novel-based"],
		mechanicSlugs: [
			"deduction",
			"narrative-choice-paragraph",
			"role-playing",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Articulate!"),
		publisherName: "Drumond Park Ltd.",
		designerName: "Andrew Bryceson",
		minPlayers: 4,
		maxPlayers: 8,
		categorySlugs: ["party-game", "trivia", "word-game"],
		mechanicSlugs: ["team-based-game"],
	},
	{
		...Seeder.generateTitleWithSlug("Bohnanza"),
		publisherName: "AMIGO",
		designerName: "Uwe Rosenberg",
		minPlayers: 2,
		maxPlayers: 7,
		categorySlugs: ["card-game", "farming", "negotiation"],
		mechanicSlugs: [
			"hand-management",
			"multi-use-cards",
			"negotiation",
			"set-collection",
			"trading",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Carcassonne Big Box 6"),
		publisherName: "Hans im Glück",
		designerName: "Klaus-Jürgen Wrede",
		minPlayers: 2,
		maxPlayers: 6,
		categorySlugs: ["city-building", "territory-building"],
		mechanicSlugs: ["area-majority-influence", "tile-placement"],
	},
	{
		...Seeder.generateTitleWithSlug("Carcassonne: Corn Circles II"),
		publisherName: " 999 Games",
		designerName: "Klaus-Jürgen Wrede",
		minPlayers: 2,
		maxPlayers: 6,
		categorySlugs: [
			"city-building",
			"expansion-for-base-game",
			"territory-building",
		],
		mechanicSlugs: ["area-majority-influence", "tile-placement"],
	},
	{
		...Seeder.generateTitleWithSlug(
			"Carcassonne: Expansion 5 - Abbey & Mayor"
		),
		publisherName: "Hans im Glück",
		designerName: "Klaus-Jürgen Wrede",
		minPlayers: 2,
		maxPlayers: 6,
		categorySlugs: [
			"expansion-for-base-game",
			"city-building",
			"territory-building",
		],
		mechanicSlugs: ["area-majority-influence", "tile-placement"],
	},
	{
		...Seeder.generateTitleWithSlug("Carcassonne: The Fruit-Bearing Trees"),
		publisherName: "Hans im Glück",
		designerName: "Klaus-Jürgen Wrede",
		minPlayers: 2,
		maxPlayers: 6,
		categorySlugs: [
			"city-building",
			"expansion-for-base-game",
			"territory-building",
		],
		mechanicSlugs: ["area-majority-influence", "tile-placement"],
	},
	{
		...Seeder.generateTitleWithSlug(
			"Clank! In! Space! Adventures: Pulsarcade"
		),
		publisherName: "Dire Wolf",
		designerName: "Paul Dennen",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["expansion-for-base-game", "science-fiction"],
		mechanicSlugs: [
			"deck-bag-and-pool-building",
			"delayed-purchase",
			"modular-board",
			"open-drafting",
			"player-elimination",
			"point-to-point-movement",
			"push-your-luck",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Clank! In! Space!: Apocalypse!"),
		publisherName: "Dire Wolf",
		designerName: "Andy Clautice",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["expansion-for-base-game", "science-fiction"],
		mechanicSlugs: [
			"deck-bag-and-pool-building",
			"delayed-purchase",
			"modular-board",
			"open-drafting",
			"player-elimination",
			"point-to-point-movement",
			"push-your-luck",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Clank! In! Space!: Cyber Station 11"),
		publisherName: "Dire Wolf",
		designerName: "Evan Lorentz",
		minPlayers: 2,
		maxPlayers: 4,
		categorySlugs: ["expansion-for-base-game", "science-fiction"],
		mechanicSlugs: [
			"deck-bag-and-pool-building",
			"delayed-purchase",
			"modular-board",
			"open-drafting",
			"player-elimination",
			"point-to-point-movement",
			"push-your-luck",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Dixit"),
		publisherName: "Marie Cardouat",
		designerName: "Jean-Louis Roubira",
		minPlayers: 3,
		maxPlayers: 8,
		categorySlugs: ["card-game", "party-game"],
		mechanicSlugs: ["race", "storytelling", "voting"],
	},
	{
		...Seeder.generateTitleWithSlug("Dune: Imperium - Bloodlines"),
		publisherName: "Dire Wolf",
		designerName: "Paul Dennen",
		minPlayers: 1,
		maxPlayers: 6,
		categorySlugs: [
			"expansion-for-base-game",
			"movies-tv-radio",
			"novel-based",
			"political",
			"science-fiction",
		],
		mechanicSlugs: [
			"card-play-conflict-resolution",
			"deck-bag-and-pool-building",
			"delayed-purchase",
			"force-commitment",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Dune: Imperium - Immortality"),
		publisherName: "Dire Wolf",
		designerName: "Paul Dennen",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: [
			"expansion-for-base-game",
			"movies-tv-radio",
			"novel-based",
			"political",
			"science-fiction",
		],
		mechanicSlugs: [
			"card-play-conflict-resolution",
			"deck-bag-and-pool-building",
			"force-commitment",
			"open-drafting",
			"race",
			"solo-solitaire-game",
			"turn-order-progressive",
			"worker-placement",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Dune: Imperium - Rise of Ix"),
		publisherName: "Dire Wolf",
		designerName: "Paul Dennen",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: [
			"expansion-for-base-game",
			"movies-tv-radio",
			"novel-based",
			"political",
			"science-fiction",
		],
		mechanicSlugs: [
			"card-play-conflict-resolution",
			"deck-bag-and-pool-building",
			"open-drafting",
			"race",
			"turn-order-progressive",
			"variable-player-powers",
			"worker-placement",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Everdell"),
		publisherName: "Starling Games",
		designerName: "James A. Wilson",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: ["animals", "card-game", "city-building", "fantasy"],
		mechanicSlugs: [
			"contracts",
			"end-game-bonuses",
			"hand-management",
			"income",
			"open-drafting",
			"set-collection",
			"solo-solitaire-game",
			"variable-set-up",
			"worker-placement",
		],
	},
	{
		...Seeder.generateTitleWithSlug(
			"Exit: The Game - Advent Calendar: The Mystery of the Ice Cave"
		),
		publisherName: "KOSMOS",
		designerName: "Inka Brand",
		minPlayers: 1,
		maxPlayers: 99,
		categorySlugs: ["deduction", "puzzle", "real-time"],
		mechanicSlugs: ["cooperative-game"],
	},
	{
		...Seeder.generateTitleWithSlug(
			"Exit: The Game - Advent Calendar: The Silent Storm"
		),
		publisherName: "KOSMOS",
		designerName: "Inka Brand",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: ["murder-mystery", "puzzle"],
		mechanicSlugs: [
			"cooperative-game",
			"deduction",
			"solo-solitaire-game",
			"storytelling",
		],
	},
	{
		...Seeder.generateTitleWithSlug(
			"Exit: The Game - Dead Man on the Orient Express"
		),
		publisherName: "KOSMOS",
		designerName: "Inka Brand",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: ["deduction", "murder-mystery", "puzzle", "real-time"],
		mechanicSlugs: ["cooperative-game", "deduction"],
	},
	{
		...Seeder.generateTitleWithSlug("Exit: The Game - The Abandoned Cabin"),
		publisherName: "KOSMOS",
		designerName: "Inka Brand",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: ["deduction", "puzzle", "real-time"],
		mechanicSlugs: ["cooperative-game"],
	},
	{
		...Seeder.generateTitleWithSlug(
			"Exit: The Game - The Disappearance of Sherlock Holmes"
		),
		publisherName: "KOSMOS",
		designerName: "Inka Brand",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: ["deduction", "puzzle", "real-time"],
		mechanicSlugs: ["cooperative-game"],
	},
	{
		...Seeder.generateTitleWithSlug(
			"Exit: The Game - The Lord of the Rings: Shadows over Middle-earth"
		),
		publisherName: "KOSMOS",
		designerName: "Inka Brand",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: ["deduction", "murder-mystery"],
		mechanicSlugs: ["cooperative-game", "deduction"],
	},
	{
		...Seeder.generateTitleWithSlug("Exit: The Game - The Pharaoh's Tomb"),
		publisherName: "KOSMOS",
		designerName: "Inka Brand",
		minPlayers: 1,
		maxPlayers: 6,
		categorySlugs: ["deduction", "puzzle", "real-time"],
		mechanicSlugs: ["cooperative-game"],
	},
	{
		...Seeder.generateTitleWithSlug("Exit: The Game - The Polar Station"),
		publisherName: "KOSMOS",
		designerName: "Inka Brand",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: ["deduction", "puzzle", "real-time"],
		mechanicSlugs: ["cooperative-game"],
	},
	{
		...Seeder.generateTitleWithSlug("Exit: The Game - The Stormy Flight"),
		publisherName: "KOSMOS",
		designerName: "Inka Brand",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: ["deduction", "puzzle"],
		mechanicSlugs: ["cooperative-game"],
	},
	{
		...Seeder.generateTitleWithSlug("Food Chain Magnate"),
		publisherName: "Splotter Spellen",
		designerName: "Jeroen Doumen",
		minPlayers: 2,
		maxPlayers: 5,
		categorySlugs: ["economic", "industry-manufacturing"],
		mechanicSlugs: [
			"delayed-purchase",
			"income",
			"market",
			"modular-board",
			"open-drafting",
			"simultaneous-action-selection",
			"victory-points-as-a-resource",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Heat: Pedal to the Metal"),
		publisherName: "Days of Wonder",
		designerName: "Asger Harding Granerud",
		minPlayers: 1,
		maxPlayers: 6,
		categorySlugs: ["racing", "sports"],
		mechanicSlugs: [
			"catch-the-leader",
			"deck-bag-and-pool-building",
			"hand-management",
			"push-your-luck",
			"race",
			"simulation",
			"simultaneous-action-selection",
			"solo-solitaire-game",
			"track-movement",
			"variable-set-up",
		],
	},
	{
		...Seeder.generateTitleWithSlug("Invincible: The Hero-Building Game"),
		publisherName: "Dire Wolf",
		designerName: "Kevin Spak",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: ["comic-book-strip"],
		mechanicSlugs: [
			"cooperative-game",
			"deck-bag-and-pool-building",
			"push-your-luck",
			"scenario-mission-campaign-game",
		],
	},
	{
		...Seeder.generateTitleWithSlug("The Isle of Cats"),
		publisherName: "The City of Games",
		designerName: "Frank West",
		minPlayers: 1,
		maxPlayers: 4,
		categorySlugs: ["animals", "fantasy", "nautical", "puzzle"],
		mechanicSlugs: [
			"closed-drafting",
			"grid-coverage",
			"hidden-victory-points",
			"income",
			"open-drafting",
			"set-collection",
			"solo-solitaire-game",
			"square-grid",
			"tile-placement",
			"turn-order-stat-based",
		],
	},
];
